<?php

/* 
 * Copyright (C) 2014 erlend
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

function mg_maildemo_menu() {
  return array(
    'admin/config/system/maildemo' => array(
      'title' => "Mail demo",
      'description' => "Test the mail interface",
      'page arguments' => array('mg_maildemo_callback'),
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'file' => 'mg_maildemo.callback.inc',
    ),
  );
}
